# Generated by Django 5.2.14 on 2026-05-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('resume_url', models.URLField(blank=True, default='')),
                ('desired_position', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='candidates_status_c98735_idx'), models.Index(fields=['created_at'], name='candidates_created_893b4a_idx')],
            },
        ),
    ]
