# Generated by Django 5.2.14 on 2026-05-10 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vacancies',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['is_open'], name='vacancies_is_open_c4e4a8_idx')],
            },
        ),
    ]
